name: trigger beqcatalogue
on:
  push:
    branches:
      - 'master'
      - 'main'
concurrency:
  group: publish
jobs:
  build:
    runs-on: ubuntu-latest
    environment: beqcatalogue
    steps:
      - uses: octokit/request-action@v2.x
        env:
          GITHUB_TOKEN: ${{ secrets.TRIGGER_BEQCATALOGUE }}
        with:
          route: POST /repos/El-Yanqui/beqcatalogue/dispatches
          event_type: 'trigger'
#test
